# .github/workflows/convert-to-pdf-html.yml

name: Convert to PDF and HTML
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - '**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          build_html: false
      - uses: EndBug/add-and-commit@v7
        with:
          add:
          author_name: 'GitHub Actions'
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
          branch: main
          message: 'File added from GitHub Action'
          add: '*.pdf'
          

